/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attachment {
  'id' : bigint,
  'url' : string,
  'kind' : string,
  'name' : string,
  'size' : bigint,
}
export interface Call {
  'id' : CallId,
  'status' : CallStatus,
  'startedAt' : Timestamp,
  'endedAt' : [] | [Timestamp],
  'callee' : UserId,
  'caller' : UserId,
}
export type CallId = bigint;
export type CallStatus = { 'ringing' : null } |
  { 'missed' : null } |
  { 'ended' : null } |
  { 'ongoing' : null } |
  { 'declined' : null };
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Message {
  'id' : MessageId,
  'status' : MessageStatus,
  'text' : string,
  'sender' : UserId,
  'timestamp' : Timestamp,
  'replyTo' : [] | [MessageId],
  'attachment' : [] | [Attachment],
  'reactions' : Array<Reaction>,
}
export type MessageId = bigint;
export type MessageStatus = { 'read' : null } |
  { 'sent' : null } |
  { 'delivered' : null };
export interface Presence {
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'online' : boolean,
}
export interface Reaction { 'emoji' : string, 'author' : UserId }
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export interface TypingStatus {
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'isTyping' : boolean,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'acceptCall' : ActorMethod<[CallId], boolean>,
  'addIceCandidate' : ActorMethod<[CallId, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMessage' : ActorMethod<[MessageId], boolean>,
  'endCall' : ActorMethod<[CallId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getAnswer' : ActorMethod<[CallId], [] | [string]>,
  'getApiDoc' : ActorMethod<[], string>,
  'getAuthorizedUsers' : ActorMethod<[], Array<UserId>>,
  'getCall' : ActorMethod<[CallId], [] | [Call]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIceCandidates' : ActorMethod<[CallId], Array<string>>,
  'getMessage' : ActorMethod<[MessageId], [] | [Message]>,
  'getOffer' : ActorMethod<[CallId], [] | [string]>,
  'getPartner' : ActorMethod<[], [] | [UserId]>,
  'getPresence' : ActorMethod<[UserId], [] | [Presence]>,
  'getTyping' : ActorMethod<[UserId], [] | [TypingStatus]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCalls' : ActorMethod<[], Array<Call>>,
  'listMessages' : ActorMethod<[], Array<Message>>,
  'markRead' : ActorMethod<[], undefined>,
  'reactToMessage' : ActorMethod<[MessageId, string], boolean>,
  'schema' : ActorMethod<[], string>,
  'searchMessages' : ActorMethod<[string], Array<Message>>,
  'sendMessage' : ActorMethod<
    [string, [] | [MessageId], [] | [Attachment]],
    MessageId
  >,
  'setAnswer' : ActorMethod<[CallId, string], undefined>,
  'setAuthorizedUsers' : ActorMethod<[Array<UserId>], undefined>,
  'setOffer' : ActorMethod<[CallId, string], undefined>,
  'setPresence' : ActorMethod<[boolean], undefined>,
  'setTyping' : ActorMethod<[boolean], undefined>,
  'startCall' : ActorMethod<[UserId], CallId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];