/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const CallId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageId = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const UserId = IDL.Principal;
export const CallStatus = IDL.Variant({
  'ringing' : IDL.Null,
  'missed' : IDL.Null,
  'ended' : IDL.Null,
  'ongoing' : IDL.Null,
  'declined' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Call = IDL.Record({
  'id' : CallId,
  'status' : CallStatus,
  'startedAt' : Timestamp,
  'endedAt' : IDL.Opt(Timestamp),
  'callee' : UserId,
  'caller' : UserId,
});
export const MessageStatus = IDL.Variant({
  'read' : IDL.Null,
  'sent' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Attachment = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'kind' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Nat,
});
export const Reaction = IDL.Record({ 'emoji' : IDL.Text, 'author' : UserId });
export const Message = IDL.Record({
  'id' : MessageId,
  'status' : MessageStatus,
  'text' : IDL.Text,
  'sender' : UserId,
  'timestamp' : Timestamp,
  'replyTo' : IDL.Opt(MessageId),
  'attachment' : IDL.Opt(Attachment),
  'reactions' : IDL.Vec(Reaction),
});
export const Presence = IDL.Record({
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'online' : IDL.Bool,
});
export const TypingStatus = IDL.Record({
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'isTyping' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acceptCall' : IDL.Func([CallId], [IDL.Bool], []),
  'addIceCandidate' : IDL.Func([CallId, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
  'endCall' : IDL.Func([CallId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAnswer' : IDL.Func([CallId], [IDL.Opt(IDL.Text)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getAuthorizedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getCall' : IDL.Func([CallId], [IDL.Opt(Call)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIceCandidates' : IDL.Func([CallId], [IDL.Vec(IDL.Text)], ['query']),
  'getMessage' : IDL.Func([MessageId], [IDL.Opt(Message)], ['query']),
  'getOffer' : IDL.Func([CallId], [IDL.Opt(IDL.Text)], ['query']),
  'getPartner' : IDL.Func([], [IDL.Opt(UserId)], ['query']),
  'getPresence' : IDL.Func([UserId], [IDL.Opt(Presence)], ['query']),
  'getTyping' : IDL.Func([UserId], [IDL.Opt(TypingStatus)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCalls' : IDL.Func([], [IDL.Vec(Call)], ['query']),
  'listMessages' : IDL.Func([], [IDL.Vec(Message)], []),
  'markRead' : IDL.Func([], [], []),
  'reactToMessage' : IDL.Func([MessageId, IDL.Text], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Opt(MessageId), IDL.Opt(Attachment)],
      [MessageId],
      [],
    ),
  'setAnswer' : IDL.Func([CallId, IDL.Text], [], []),
  'setAuthorizedUsers' : IDL.Func([IDL.Vec(UserId)], [], []),
  'setOffer' : IDL.Func([CallId, IDL.Text], [], []),
  'setPresence' : IDL.Func([IDL.Bool], [], []),
  'setTyping' : IDL.Func([IDL.Bool], [], []),
  'startCall' : IDL.Func([UserId], [CallId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const CallId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageId = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const UserId = IDL.Principal;
  const CallStatus = IDL.Variant({
    'ringing' : IDL.Null,
    'missed' : IDL.Null,
    'ended' : IDL.Null,
    'ongoing' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Call = IDL.Record({
    'id' : CallId,
    'status' : CallStatus,
    'startedAt' : Timestamp,
    'endedAt' : IDL.Opt(Timestamp),
    'callee' : UserId,
    'caller' : UserId,
  });
  const MessageStatus = IDL.Variant({
    'read' : IDL.Null,
    'sent' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Attachment = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'kind' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
  });
  const Reaction = IDL.Record({ 'emoji' : IDL.Text, 'author' : UserId });
  const Message = IDL.Record({
    'id' : MessageId,
    'status' : MessageStatus,
    'text' : IDL.Text,
    'sender' : UserId,
    'timestamp' : Timestamp,
    'replyTo' : IDL.Opt(MessageId),
    'attachment' : IDL.Opt(Attachment),
    'reactions' : IDL.Vec(Reaction),
  });
  const Presence = IDL.Record({
    'userId' : UserId,
    'updatedAt' : Timestamp,
    'online' : IDL.Bool,
  });
  const TypingStatus = IDL.Record({
    'userId' : UserId,
    'updatedAt' : Timestamp,
    'isTyping' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acceptCall' : IDL.Func([CallId], [IDL.Bool], []),
    'addIceCandidate' : IDL.Func([CallId, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
    'endCall' : IDL.Func([CallId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAnswer' : IDL.Func([CallId], [IDL.Opt(IDL.Text)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getAuthorizedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getCall' : IDL.Func([CallId], [IDL.Opt(Call)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIceCandidates' : IDL.Func([CallId], [IDL.Vec(IDL.Text)], ['query']),
    'getMessage' : IDL.Func([MessageId], [IDL.Opt(Message)], ['query']),
    'getOffer' : IDL.Func([CallId], [IDL.Opt(IDL.Text)], ['query']),
    'getPartner' : IDL.Func([], [IDL.Opt(UserId)], ['query']),
    'getPresence' : IDL.Func([UserId], [IDL.Opt(Presence)], ['query']),
    'getTyping' : IDL.Func([UserId], [IDL.Opt(TypingStatus)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCalls' : IDL.Func([], [IDL.Vec(Call)], ['query']),
    'listMessages' : IDL.Func([], [IDL.Vec(Message)], []),
    'markRead' : IDL.Func([], [], []),
    'reactToMessage' : IDL.Func([MessageId, IDL.Text], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Opt(MessageId), IDL.Opt(Attachment)],
        [MessageId],
        [],
      ),
    'setAnswer' : IDL.Func([CallId, IDL.Text], [], []),
    'setAuthorizedUsers' : IDL.Func([IDL.Vec(UserId)], [], []),
    'setOffer' : IDL.Func([CallId, IDL.Text], [], []),
    'setPresence' : IDL.Func([IDL.Bool], [], []),
    'setTyping' : IDL.Func([IDL.Bool], [], []),
    'startCall' : IDL.Func([UserId], [CallId], []),
  });
};

export const init = ({ IDL }) => { return []; };